const BOT_METHODS = [
  'getUpdates',
  'setWebhook',
  'deleteWebhook',
  'getWebhookInfo',
  'getMe',
  'logOut',
  'close',
  'sendMessage',
  'forwardMessage',
  'forwardMessages',
  'copyMessage',
  'copyMessages',
  'sendPhoto',
  'sendAudio',
  'sendDocument',
  'sendVideo',
  'sendAnimation',
  'sendVoice',
  'sendVideoNote',
  'sendPaidMedia',
  'sendMediaGroup',
  'sendLocation',
  'sendVenue',
  'sendContact',
  'sendPoll',
  'sendDice',
  'sendChatAction',
  'setMessageReaction',
  'getUserProfilePhotos',
  'getFile',
  'banChatMember',
  'unbanChatMember',
  'restrictChatMember',
  'promoteChatMember',
  'setChatAdministratorCustomTitle',
  'banChatSenderChat',
  'unbanChatSenderChat',
  'setChatPermissions',
  'exportChatInviteLink',
  'createChatInviteLink',
  'editChatInviteLink',
  'createChatSubscriptionInviteLink',
  'editChatSubscriptionInviteLink',
  'revokeChatInviteLink',
  'approveChatJoinRequest',
  'declineChatJoinRequest',
  'setChatPhoto',
  'deleteChatPhoto',
  'setChatTitle',
  'setChatDescription',
  'pinChatMessage',
  'unpinChatMessage',
  'unpinAllChatMessages',
  'leaveChat',
  'getChat',
  'getChatAdministrators',
  'getChatMemberCount',
  'getChatMember',
  'setChatStickerSet',
  'deleteChatStickerSet',
  'getForumTopicIconStickers',
  'createForumTopic',
  'editForumTopic',
  'closeForumTopic',
  'reopenForumTopic',
  'deleteForumTopic',
  'unpinAllForumTopicMessages',
  'editGeneralForumTopic',
  'closeGeneralForumTopic',
  'reopenGeneralForumTopic',
  'hideGeneralForumTopic',
  'unhideGeneralForumTopic',
  'unpinAllGeneralForumTopicMessages',
  'answerCallbackQuery',
  'getUserChatBoosts',
  'getBusinessConnection',
  'setMyCommands',
  'deleteMyCommands',
  'getMyCommands',
  'setMyName',
  'getMyName',
  'setMyDescription',
  'getMyDescription',
  'setMyShortDescription',
  'getMyShortDescription',
  'setChatMenuButton',
  'getChatMenuButton',
  'setMyDefaultAdministratorRights',
  'getMyDefaultAdministratorRights',
  'editMessageText',
  'editMessageCaption',
  'editMessageMedia',
  'editMessageLiveLocation',
  'stopMessageLiveLocation',
  'editMessageReplyMarkup',
  'stopPoll',
  'deleteMessage',
  'deleteMessages',
  'sendSticker',
  'getStickerSet',
  'getCustomEmojiStickers',
  'uploadStickerFile',
  'createNewStickerSet',
  'addStickerToSet',
  'setStickerPositionInSet',
  'deleteStickerFromSet',
  'replaceStickerInSet',
  'setStickerEmojiList',
  'setStickerKeywords',
  'setStickerMaskPosition',
  'setStickerSetTitle',
  'setStickerSetThumbnail',
  'setCustomEmojiStickerSetThumbnail',
  'deleteStickerSet',
  'answerInlineQuery',
  'answerWebAppQuery',
  'sendInvoice',
  'createInvoiceLink',
  'answerShippingQuery',
  'answerPreCheckoutQuery',
  'getStarTransactions',
  'refundStarPayment',
  'setPassportDataErrors',
  'sendGame',
  'setGameScore',
  'getGameHighScores',
] as const

type BotMethod = (typeof BOT_METHODS)[number]

// 不想做nlp分析了 ()
export const RETURN_TYPE_OF_BOT_METHODS: Record<BotMethod, string> = {
  addStickerToSet: 'File',
  answerCallbackQuery: 'True',
  answerInlineQuery: 'True',
  answerPreCheckoutQuery: 'True',
  answerShippingQuery: 'True',
  answerWebAppQuery: 'True',
  approveChatJoinRequest: 'True',
  banChatMember: 'True',
  banChatSenderChat: 'True',
  close: 'True',
  closeForumTopic: 'True',
  closeGeneralForumTopic: 'True',
  copyMessage: 'MessageId',
  copyMessages: 'Array of MessageId',
  createChatInviteLink: 'ChatInviteLink',
  createChatSubscriptionInviteLink: 'ChatInviteLink',
  createForumTopic: 'ForumTopic',
  createInvoiceLink: 'String',
  createNewStickerSet: 'True',
  declineChatJoinRequest: 'True',
  deleteChatPhoto: 'True',
  deleteChatStickerSet: 'True',
  deleteForumTopic: 'True',
  deleteMessage: 'True',
  deleteMessages: 'True',
  deleteMyCommands: 'True',
  deleteStickerFromSet: 'True',
  deleteStickerSet: 'True',
  deleteWebhook: 'True',
  editChatInviteLink: 'ChatInviteLink',
  editChatSubscriptionInviteLink: 'ChatInviteLink',
  editForumTopic: 'True',
  editGeneralForumTopic: 'True',
  editMessageCaption: 'Message or True',
  editMessageLiveLocation: 'Message or True',
  editMessageMedia: 'Message or True',
  editMessageReplyMarkup: 'Message or True',
  editMessageText: 'Message or True',
  exportChatInviteLink: 'String',
  forwardMessage: 'Message',
  forwardMessages: 'Array of MessageId',
  getBusinessConnection: 'BusinessConnection',
  getChat: 'ChatFullInfo',
  getChatAdministrators: 'Array of ChatMember',
  getChatMember: 'ChatMember',
  getChatMemberCount: 'Integer',
  getChatMenuButton: 'MenuButton',
  getCustomEmojiStickers: 'Array of Sticker',
  getFile: 'File',
  getForumTopicIconStickers: 'Array of Sticker',
  getGameHighScores: 'Array of GameHighScore',
  getMe: 'User',
  getMyCommands: 'Array of BotCommand',
  getMyDefaultAdministratorRights: 'ChatAdministratorRights',
  getMyDescription: 'BotDescription',
  getMyShortDescription: 'BotShortDescription',
  getMyName: 'BotName',
  getStarTransactions: 'StarTransactions',
  getStickerSet: 'StickerSet',
  getUpdates: 'Array of Update',
  getUserChatBoosts: 'UserChatBoosts',
  getUserProfilePhotos: 'UserProfilePhotos',
  getWebhookInfo: 'WebhookInfo',
  hideGeneralForumTopic: 'True',
  leaveChat: 'True',
  logOut: 'True',
  pinChatMessage: 'True',
  promoteChatMember: 'True',
  refundStarPayment: 'True',
  reopenForumTopic: 'True',
  reopenGeneralForumTopic: 'True',
  replaceStickerInSet: 'True',
  restrictChatMember: 'True',
  revokeChatInviteLink: 'ChatInviteLink',
  sendAnimation: 'Message',
  sendAudio: 'Message',
  sendChatAction: 'True',
  sendContact: 'Message',
  sendDice: 'Message',
  sendDocument: 'Message',
  sendGame: 'Message',
  sendInvoice: 'Message',
  sendLocation: 'Message',
  sendMediaGroup: 'Array of Message',
  sendMessage: 'Message',
  sendPaidMedia: 'Message',
  sendPhoto: 'Message',
  sendPoll: 'Message',
  sendSticker: 'Message',
  sendVenue: 'Message',
  sendVideo: 'Message',
  sendVideoNote: 'Message',
  sendVoice: 'Message',
  setChatAdministratorCustomTitle: 'True',
  setChatDescription: 'True',
  setChatMenuButton: 'True',
  setChatPermissions: 'True',
  setChatPhoto: 'True',
  setChatStickerSet: 'True',
  setChatTitle: 'True',
  setCustomEmojiStickerSetThumbnail: 'True',
  setGameScore: 'Message or True',
  setMessageReaction: 'True',
  setMyCommands: 'True',
  setMyDefaultAdministratorRights: 'True',
  setMyDescription: 'True',
  setMyName: 'True',
  setMyShortDescription: 'True',
  setPassportDataErrors: 'True',
  setStickerEmojiList: 'True',
  setStickerKeywords: 'True',
  setStickerMaskPosition: 'True',
  setStickerPositionInSet: 'True',
  setStickerSetThumbnail: 'True',
  setStickerSetTitle: 'True',
  setWebhook: 'True',
  stopMessageLiveLocation: 'Message or True',
  stopPoll: 'Poll',
  unbanChatMember: 'True',
  unbanChatSenderChat: 'True',
  unhideGeneralForumTopic: 'True',
  unpinAllChatMessages: 'True',
  unpinAllForumTopicMessages: 'True',
  unpinAllGeneralForumTopicMessages: 'True',
  unpinChatMessage: 'True',
  uploadStickerFile: 'File',
}
